export const DELETE_ITEM = 'DELETE_ITEM';
export const GET_CALENDAR_DATE = 'GET_CALENDAR_DATE';
export const SET_DATE_EVENTS = 'SET_DATE_EVENTS';
export const GET_SELECTED_DATE_EVENTS = 'GET_SELECTED_DATE_EVENTS';
export const LOAD_FONTS = 'LOAD_FONTS';